pluto: move struct keyword_auto from ipsecconf/keywords.h to pluto_constants.h
otherwise need to add ipsecconf/keywords.h in connections.h
which would lead conflicting definations of struct keyword
So this is a compromise for now

/home/build/libreswan/include/keywords.h:61:8: error: redefinition of 'struct keyword'
   61 | struct keyword {
      |        ^~~~~~~
/home/build/libreswan/include/ipsecconf/keywords.h:377:8: note: originally defined here
  377 | struct keyword {
      |        ^~~~~~~